[package]
name = "tokio-io-pool"
version = "0.1.6"
edition = "2018"

description = "Alternative tokio thread pool for executing short, I/O-heavy futures efficiently"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/tokio-io-pool"
repository = "https://github.com/jonhoo/tokio-io-pool.git"

keywords = ["futures", "tokio", "threadpool", "io"]
categories = ["asynchronous", "concurrency", "network-programming"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/tokio-io-pool" }
maintenance = { status = "experimental" }

[dependencies]
futures-core-preview = "0.3.0-alpha.17"
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "jonhoo/less-enter" }
num_cpus = "1.8"
tokio-executor = { git = "https://github.com/tokio-rs/tokio.git", branch = "jonhoo/less-enter" }

[dev-dependencies]
tokio-current-thread = { git = "https://github.com/tokio-rs/tokio.git", branch = "jonhoo/less-enter" }
futures-preview = "0.3.0-alpha.17"
futures-util-preview = "0.3.0-alpha.17"
